### ISSUE TITLE
Interval, fastestInterval and maxWaitTime not working.

### ISSUE THREAD

**Issue by thomaslc66** [timfpark/react-native-location#90]
First of all what's the purpose of all those attributes ?

Interval seems to be avoided when fastestInterval is set but maxWaitTime seems to me like an interval too.

But the main concern here is even if i'm setting all of those parameters the location is not updated based on one of those delay.

If you look at this image, you'll see a geofence, a polyline and the user position.
![image](https://user-images.githubusercontent.com/9827392/64632910-569e2400-d3fa-11e9-86e6-dd3ed4476248.png)
When the user enter the geofence it trigger an audio message, but with this library it's not working.

Why ? because although the blue do is inside the geofence, the last position is defined by the end of the polyline. So the user seems to be into the geofence, but the maxWaitTime, interval or fastestInterval are not triggered to update the real position of the user and the phone thinks the last position is outside (corresponding to the last part of the blue line)

Why the position is not updated to the real position of the blue dot even if i put : 
````
    RNLocation.configure({
      distanceFilter: 1.0,
      interval: 1500,
      fastestInterval: 1000,
      maxWaitTime: 2000,
      desiredAccuracy: {
        ios: 'best',
        android: 'balancedPowerAccuracy' //balancedPowerAccuracy, highAccuracy, lowPower, or noPower
      },
      headingOrientation: 'portrait',
      pausesLocationUpdatesAutomatically: false
    });
````

**Comment by matt-oakes** [comment]
If you want to get a new location every second, then I recommend not including the `distanceFilter`. If you include that, it may stop a location being sent to you if the devices decided it hasn't moved enough.

This library doesn't do anything special with the location configuration parameters. It just passes these on to the system APIs and passes back every location the system provides to you. Because of this, I recommend that you read up on the iOS and Android documentation to really understand what each of the parameters are doing.

Let me know if you need any more help with these or if removing the distance filter doesn't work.
